title: Aqua Store Pro
logo: /assets/img/original_logo-removebg-preview.png
description: Plants, live food and everything fishkeeping
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: aquastorepro
collections_dir: products
collections:
  livestock:
    output: true
  plants:
    output: true
  builds:
    output: true


plugins:
 - jekyll-feed
